version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false

    post_install:
      - poetry install --only doc
      - pip install mkdocs-material

mkdocs:
  configuration: mkdocs.yml